In [1]:
import numpy as np
import torch

In [2]:
inputs = np.array([[73,67,43],
                   [91,88,64],
                   [87,134,58],
                   [102,43,37],
                   [69,96,70]],dtype='float32')

In [3]:
targets = np.array([[56],
                    [81],
                    [119],
                    [22],
                    [103]],dtype='float32')

In [4]:
 # Convert inputs and targets to tensors
inputs = torch.from_numpy(inputs)
print(inputs)
targets = torch.from_numpy(targets)
print(targets)

tensor([[ 73.,  67.,  43.],
        [ 91.,  88.,  64.],
        [ 87., 134.,  58.],
        [102.,  43.,  37.],
        [ 69.,  96.,  70.]])
tensor([[ 56.],
        [ 81.],
        [119.],
        [ 22.],
        [103.]])


In [5]:
 # Weights and biases
w = torch.randn(1,3,requires_grad =True)
print(w)
b = torch.randn(1,requires_grad=True)
print(b)

tensor([[ 0.1037,  1.2399, -0.9699]], requires_grad=True)
tensor([0.3688], requires_grad=True)


In [6]:
# Define the model
def model(x):
  return torch.mm(x,w.t(),out=None) +b

In [7]:
# Generate predictions
# Compare with targets

preds = model(inputs)
print("Prediction :",preds)
print("Targets :",targets)

Prediction : tensor([[ 49.3081],
        [ 56.8453],
        [119.2854],
        [ 28.3771],
        [ 58.6637]], grad_fn=<AddBackward0>)
Targets : tensor([[ 56.],
        [ 81.],
        [119.],
        [ 22.],
        [103.]])


In [8]:
# MSE loss
# Compute loss
def mse(P,T):
  diff = 0
  i=0
  sum=0
  n=len(T)
  for k in range(0,n):
    i+=1
    diff = T[k] - P[k]
    square = diff*diff
    sum+=square
  mean = sum/i
  return mean

output = mse(preds,targets)
print("Loss :",output)

Loss : tensor([526.9378], grad_fn=<DivBackward0>)


In [9]:
# Compute gradients
print("Gradient :",output.backward())

Gradient : None


In [10]:
# Gradients for weights
print(w)
print(w.grad)

tensor([[ 0.1037,  1.2399, -0.9699]], requires_grad=True)
tensor([[-2028.2034, -2607.1226, -1873.8776]])


In [11]:
# Gradients for bias
print(b)
print(b.grad)

tensor([0.3688], requires_grad=True)
tensor([-27.4082])


In [12]:
# Compute gradients
with torch.no_grad():
  w-=w.grad*1e-5
  b-=b.grad*1e-5
  w.grad.zero_()
  b.grad.zero_()
print(w)
print(b)

tensor([[ 0.1240,  1.2660, -0.9511]], requires_grad=True)
tensor([0.3691], requires_grad=True)


In [13]:
# Generate predictions
# Calculate the loss
new_preds = model(inputs)
new_loss = mse(new_preds,targets)
print("New Loss :",new_loss)

New Loss : tensor([408.1712], grad_fn=<DivBackward0>)


In [14]:
# Train for 100 epochs
for i in range(200):
  preds = model(inputs)
  loss = mse(preds,targets)
  loss.backward()
  with torch.no_grad():
    w-=w.grad * 1e-5
    b-=b.grad * 1e-5
    w.grad.zero_()
    b.grad.zero_()

In [15]:
# Calculate loss
preds = model(inputs)
loss = mse(preds,targets)
print(loss)

tensor([136.6159], grad_fn=<DivBackward0>)


Pytorch_Built_Ins

In [16]:
 # Imports
import torch.nn as nn
print(inputs)
print(targets)


tensor([[ 73.,  67.,  43.],
        [ 91.,  88.,  64.],
        [ 87., 134.,  58.],
        [102.,  43.,  37.],
        [ 69.,  96.,  70.]])
tensor([[ 56.],
        [ 81.],
        [119.],
        [ 22.],
        [103.]])


In [17]:
def model1(x):
  return x @ w.t() +b

In [18]:
preds = model(inputs)
print("Prediction :",preds)
print("Targets :",targets)

Prediction : tensor([[ 58.3599],
        [ 74.0679],
        [135.2841],
        [ 26.7643],
        [ 84.5180]], grad_fn=<AddBackward0>)
Targets : tensor([[ 56.],
        [ 81.],
        [119.],
        [ 22.],
        [103.]])


In [19]:
loss = nn.MSELoss()
output = loss(preds,targets)
output.backward()
print("Loss :",output)

Loss : tensor(136.6159, grad_fn=<MseLossBackward0>)


In [20]:
print(w)
print(w.grad)
print(b)
print(b.grad)

tensor([[-0.1263,  1.2663, -0.4100]], requires_grad=True)
tensor([[  67.5475,   64.3011, -206.0647]])
tensor([0.3706], requires_grad=True)
tensor([-0.8023])


In [21]:
for i in range(100):
    preds = model(inputs)
    loss = mse(preds, targets)
    loss.backward()
    with torch.no_grad():
        w -= w.grad * 1e-5
        b -= b.grad * 1e-5
        w.grad.zero_()
        b.grad.zero_()

In [22]:
preds = model1(inputs)
loss = mse(preds,targets)
 
print(loss)

tensor([93.8278], grad_fn=<DivBackward0>)
