In [1]:
import numpy as np
import pandas as pd

In [2]:
from sklearn import linear_model
from sklearn.model_selection import cross_val_score
from sklearn.tree import DecisionTreeClassifier
from sklearn.datasets import load_breast_cancer
Data = load_breast_cancer()
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import BernoulliNB

In [3]:
lr=linear_model.LogisticRegression()
dt=DecisionTreeClassifier()
bn=BernoulliNB()

In [4]:
df=pd.DataFrame(Data.data, columns=Data.feature_names)
df["target"]=pd.Series(Data.target)

In [5]:
df.head()

mean radius  mean texture  mean perimeter  mean area  mean smoothness  \
0        17.99         10.38          122.80     1001.0          0.11840   
1        20.57         17.77          132.90     1326.0          0.08474   
2        19.69         21.25          130.00     1203.0          0.10960   
3        11.42         20.38           77.58      386.1          0.14250   
4        20.29         14.34          135.10     1297.0          0.10030   

   mean compactness  mean concavity  mean concave points  mean symmetry  \
0           0.27760          0.3001              0.14710         0.2419   
1           0.07864          0.0869              0.07017         0.1812   
2           0.15990          0.1974              0.12790         0.2069   
3           0.28390          0.2414              0.10520         0.2597   
4           0.13280          0.1980              0.10430         0.1809   

   mean fractal dimension  ...  worst texture  worst perimeter  worst area  \
0                 0.07871  ...          17.33           184.60      2019.0   
1                 0.05667  ...          23.41           158.80      1956.0   
2                 0.05999  ...          25.53           152.50      1709.0   
3                 0.09744  ...          26.50            98.87       567.7   
4                 0.05883  ...          16.67           152.20      1575.0   

   worst smoothness  worst compactness  worst concavity  worst concave points  \
0            0.1622             0.6656           0.7119                0.2654   
1            0.1238             0.1866           0.2416                0.1860   
2            0.1444             0.4245           0.4504                0.2430   
3            0.2098             0.8663           0.6869                0.2575   
4            0.1374             0.2050           0.4000                0.1625   

   worst symmetry  worst fractal dimension  target  
0          0.4601                  0.11890       0  
1          0.2750                  0.08902       0  
2          0.3613                  0.08758       0  
3          0.6638                  0.17300       0  
4          0.2364                  0.07678       0  

[5 rows x 31 columns]

In [6]:
df2=df.sample(frac=1)

In [7]:
df2.shape

(569, 31)

In [8]:
hold_on_data=df2.iloc[0:285,:]

In [9]:
hold_on_data.shape

(285, 31)

In [10]:
hold_on_data

mean radius  mean texture  mean perimeter  mean area  mean smoothness  \
334       12.300         19.02           77.88      464.4          0.08313   
362       12.760         18.84           81.87      496.6          0.09676   
308       13.500         12.71           85.69      566.2          0.07376   
434       14.860         16.94           94.89      673.7          0.08924   
221       13.560         13.90           88.59      561.3          0.10510   
..           ...           ...             ...        ...              ...   
467        9.668         18.10           61.06      286.3          0.08311   
51        13.640         16.34           87.21      571.8          0.07685   
106       11.640         18.33           75.17      412.5          0.11420   
65        14.780         23.94           97.40      668.3          0.11720   
259       15.530         33.56          103.70      744.9          0.10630   

     mean compactness  mean concavity  mean concave points  mean symmetry  \
334           0.04202        0.007756             0.008535         0.1539   
362           0.07952        0.026880             0.017810         0.1759   
308           0.03614        0.002758             0.004419         0.1365   
434           0.07074        0.033460             0.028770         0.1573   
221           0.11920        0.078600             0.044510         0.1962   
..                ...             ...                  ...            ...   
467           0.05428        0.014790             0.005769         0.1680   
51            0.06059        0.018570             0.017230         0.1353   
106           0.10170        0.070700             0.034850         0.1801   
65            0.14790        0.126700             0.090290         0.1953   
259           0.16390        0.175100             0.083990         0.2091   

     mean fractal dimension  ...  worst texture  worst perimeter  worst area  \
334                 0.05945  ...          28.46            84.53       544.3   
362                 0.06183  ...          25.99            87.82       579.7   
308                 0.05335  ...          16.94            95.48       698.7   
434                 0.05703  ...          20.54           102.30       777.5   
221                 0.06303  ...          17.13           101.10       686.6   
..                      ...  ...            ...              ...         ...   
467                 0.06412  ...          24.62            71.11       380.2   
51                  0.05953  ...          23.19            96.08       656.7   
106                 0.06520  ...          29.26            85.51       521.7   
65                  0.06654  ...          33.39           114.60       925.1   
259                 0.06650  ...          49.54           126.30      1035.0   

     worst smoothness  worst compactness  worst concavity  \
334           0.12220            0.09052          0.03619   
362           0.12980            0.18390          0.12550   
308           0.09023            0.05836          0.01379   
434           0.12180            0.15500          0.12200   
221           0.13760            0.26980          0.25770   
..                ...                ...              ...   
467           0.13880            0.12550          0.06409   
51            0.10890            0.15820          0.10500   
106           0.16880            0.26600          0.28730   
65            0.16480            0.34160          0.30240   
259           0.18830            0.55640          0.57030   

     worst concave points  worst symmetry  worst fractal dimension  target  
334               0.03983          0.2554                  0.07207       1  
362               0.08312          0.2744                  0.07238       1  
308               0.02210          0.2267                  0.06192       1  
434               0.07971          0.2525                  0.06827       1  
221               0.09090          0.3065                  0.081

In [11]:
df1=df2.iloc[286:569,:]

In [12]:
y=df1.iloc[:,-1]

In [13]:
y

327    1
416    1
226    1
136    1
2      0
      ..
125    1
356    1
282    0
188    1
103    1
Name: target, Length: 283, dtype: int64

In [14]:
X=df1.iloc[:,:-1]

In [15]:
X

mean radius  mean texture  mean perimeter  mean area  mean smoothness  \
327       12.030         17.93           76.09      446.0          0.07683   
416        9.405         21.70           59.60      271.2          0.10440   
226       10.440         15.46           66.62      329.6          0.10530   
136       11.710         16.67           74.72      423.6          0.10510   
2         19.690         21.25          130.00     1203.0          0.10960   
..           ...           ...             ...        ...              ...   
125       13.850         17.21           88.44      588.7          0.08785   
356       13.050         18.59           85.09      512.0          0.10820   
282       19.400         18.18          127.20     1145.0          0.10370   
188       11.810         17.39           75.27      428.9          0.10070   
103        9.876         19.40           63.95      298.3          0.10050   

     mean compactness  mean concavity  mean concave points  mean symmetry  \
327           0.03892        0.001546             0.005592         0.1382   
416           0.06159        0.020470             0.012570         0.2025   
226           0.07722        0.006643             0.012160         0.1788   
136           0.06095        0.035920             0.026000         0.1339   
2             0.15990        0.197400             0.127900         0.2069   
..                ...             ...                  ...            ...   
125           0.06136        0.014200             0.011410         0.1614   
356           0.13040        0.096030             0.056030         0.2035   
282           0.14420        0.162600             0.094640         0.1893   
188           0.05562        0.023530             0.015530         0.1718   
103           0.09697        0.061540             0.030290         0.1945   

     mean fractal dimension  ...  worst radius  worst texture  \
327                 0.06070  ...         13.07          22.25   
416                 0.06601  ...         10.85          31.24   
226                 0.06450  ...         11.52          19.80   
136                 0.05945  ...         13.33          25.48   
2                   0.05999  ...         23.57          25.53   
..                      ...  ...           ...            ...   
125                 0.05890  ...         15.49          23.58   
356                 0.06501  ...         14.19          24.85   
282                 0.05892  ...         23.79          28.65   
188                 0.05780  ...         12.57          26.48   
103                 0.06322  ...         10.76          26.83   

     worst perimeter  worst area  worst smoothness  worst compactness  \
327            82.74       523.4            0.1013             0.0739   
416            68.73       359.4            0.1526             0.1193   
226            73.47       395.4            0.1341             0.1153   
136            86.16       546.7            0.1271             0.1028   
2             152.50      1709.0            0.1444             0.4245   
..               ...         ...               ...                ...   
125           100.30       725.9            0.1157             0.1350   
356            94.22       591.2            0.1343             0.2658   
282           152.40      1628.0            0.1518             0.3749   
188            79.57       489.5            0.1356             0.1000   
103            72.22       361.2            0.1559             0.2302   

     worst concavity  worst concave points  worst symmetry  \
327         0.007732               0.02796          0.2171   
416         0.061410               0.03770          0.2872   
226         0.026390               0.04464          0.2615   
136         0.104600               0.06968          0.1712   
2           0.450400               0.24300          0.3613   
..               ...                   ...             ...   
125         0.081150               0.05104         

In [16]:
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
X=sc.fit_transform(X)

In [17]:
X

array([[-0.5965309 , -0.3303782 , -0.6545336 , ..., -1.36959244,
        -1.21345976, -0.77686357],
       [-1.34830434,  0.5563289 , -1.33698428, ..., -1.21890431,
        -0.03088432, -0.08132967],
       [-1.05189081, -0.91132424, -1.04645646, ..., -1.11153515,
        -0.46443908, -0.10054332],
       ...,
       [ 1.51416254, -0.271578  ,  1.46069105, ...,  1.6819196 ,
         1.18036985, -0.36514264],
       [-0.65953667, -0.45738665, -0.68846989, ..., -1.13597943,
         0.52244628, -1.0299347 ],
       [-1.21341471,  0.01536701, -1.15695635, ..., -0.29388958,
        -0.45263019,  0.02077712]])

In [18]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33)

In [19]:
lr.fit(X_train,y_train)
dt.fit(X_train,y_train)
bn.fit(X_train,y_train)

BernoulliNB()

In [20]:
h_X=hold_on_data.iloc[:,:-1]
h_y=hold_on_data.iloc[:,-1]

In [21]:
h_X

mean radius  mean texture  mean perimeter  mean area  mean smoothness  \
334       12.300         19.02           77.88      464.4          0.08313   
362       12.760         18.84           81.87      496.6          0.09676   
308       13.500         12.71           85.69      566.2          0.07376   
434       14.860         16.94           94.89      673.7          0.08924   
221       13.560         13.90           88.59      561.3          0.10510   
..           ...           ...             ...        ...              ...   
467        9.668         18.10           61.06      286.3          0.08311   
51        13.640         16.34           87.21      571.8          0.07685   
106       11.640         18.33           75.17      412.5          0.11420   
65        14.780         23.94           97.40      668.3          0.11720   
259       15.530         33.56          103.70      744.9          0.10630   

     mean compactness  mean concavity  mean concave points  mean symmetry  \
334           0.04202        0.007756             0.008535         0.1539   
362           0.07952        0.026880             0.017810         0.1759   
308           0.03614        0.002758             0.004419         0.1365   
434           0.07074        0.033460             0.028770         0.1573   
221           0.11920        0.078600             0.044510         0.1962   
..                ...             ...                  ...            ...   
467           0.05428        0.014790             0.005769         0.1680   
51            0.06059        0.018570             0.017230         0.1353   
106           0.10170        0.070700             0.034850         0.1801   
65            0.14790        0.126700             0.090290         0.1953   
259           0.16390        0.175100             0.083990         0.2091   

     mean fractal dimension  ...  worst radius  worst texture  \
334                 0.05945  ...         13.35          28.46   
362                 0.06183  ...         13.75          25.99   
308                 0.05335  ...         14.97          16.94   
434                 0.05703  ...         16.31          20.54   
221                 0.06303  ...         14.98          17.13   
..                      ...  ...           ...            ...   
467                 0.06412  ...         11.15          24.62   
51                  0.05953  ...         14.67          23.19   
106                 0.06520  ...         13.14          29.26   
65                  0.06654  ...         17.31          33.39   
259                 0.06650  ...         18.49          49.54   

     worst perimeter  worst area  worst smoothness  worst compactness  \
334            84.53       544.3           0.12220            0.09052   
362            87.82       579.7           0.12980            0.18390   
308            95.48       698.7           0.09023            0.05836   
434           102.30       777.5           0.12180            0.15500   
221           101.10       686.6           0.13760            0.26980   
..               ...         ...               ...                ...   
467            71.11       380.2           0.13880            0.12550   
51             96.08       656.7           0.10890            0.15820   
106            85.51       521.7           0.16880            0.26600   
65            114.60       925.1           0.16480            0.34160   
259           126.30      1035.0           0.18830            0.55640   

     worst concavity  worst concave points  worst symmetry  \
334          0.03619               0.03983          0.2554   
362          0.12550               0.08312          0.2744   
308          0.01379               0.02210          0.2267   
434          0.12200               0.07971          0.2525   
221          0.25770               0.09090          0.3065   
..               ...                   ...             ...   
467          0.06409               0.02500         

In [22]:
h_X=sc.fit_transform(h_X)

In [23]:
x1=lr.predict(h_X)
x2=dt.predict(h_X)
x3=bn.predict(h_X)

In [24]:
x1

array([1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 0, 1, 1, 0, 1, 0, 1, 1, 1, 1, 0, 0,
       1, 1, 0, 1, 1, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1,
       1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0,
       1, 0, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 0, 1,
       1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1,
       0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 1, 0, 1,
       1, 1, 1, 0, 1, 0, 1, 0, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 0, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 1,
       1, 1, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1,
       1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 0, 0, 1, 1, 1, 0, 0, 0, 1,
       0, 1, 0, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0, 1,
       1, 0, 1, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0])

In [25]:
x2

array([1, 1, 1, 1, 1, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 0, 1, 1, 1, 1, 0, 0,
       1, 1, 0, 1, 1, 0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1,
       1, 0, 1, 0, 0, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1,
       1, 0, 1, 0, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0, 1,
       1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1,
       0, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 0, 1,
       1, 1, 1, 0, 1, 0, 1, 0, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 0, 1,
       1, 1, 0, 1, 0, 1, 1, 1, 0, 0, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 1,
       1, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1,
       0, 0, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1,
       0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1,
       1, 0, 1, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0])

In [26]:
x3

array([1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1, 0, 1, 1, 1, 1, 0, 0,
       1, 1, 0, 1, 1, 0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1,
       1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 0, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1,
       1, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 0, 1, 1, 1, 0, 1, 1, 0, 0, 1,
       1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1,
       0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 1, 0, 1,
       1, 1, 1, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 0, 0, 1,
       1, 1, 0, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 1,
       1, 1, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1,
       0, 0, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1,
       0, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0, 1,
       1, 0, 1, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0])

In [27]:
df3=pd.DataFrame(data=[x1,x2,x3])

In [28]:
df4=df3.T

In [29]:
df4

0  1  2
0    1  1  1
1    1  1  1
2    1  1  1
3    1  1  1
4    1  1  1
..  .. .. ..
280  1  1  1
281  1  1  1
282  1  1  1
283  0  0  0
284  0  0  0

[285 rows x 3 columns]

In [30]:
lr2=LogisticRegression()

In [31]:
df4_X=df4.iloc[:,:]
df4_Y=h_y

In [32]:
df4_X

0  1  2
0    1  1  1
1    1  1  1
2    1  1  1
3    1  1  1
4    1  1  1
..  .. .. ..
280  1  1  1
281  1  1  1
282  1  1  1
283  0  0  0
284  0  0  0

[285 rows x 3 columns]

In [33]:
df4_Y

334    1
362    1
308    1
434    1
221    1
      ..
467    1
51     1
106    1
65     0
259    0
Name: target, Length: 285, dtype: int64

In [34]:
lr2.fit(df4_X,df4_Y)

LogisticRegression()

In [35]:
X_test=sc.fit_transform(X_test)

In [36]:
X_test

array([[-0.77842701, -0.37642636, -0.79795229, ..., -0.51110125,
         0.07207214, -0.49746925],
       [-0.49735268, -1.6711182 , -0.53166234, ..., -0.40551847,
        -0.17539298, -1.03564432],
       [-1.21292108,  0.08096477, -1.15551773, ..., -0.35097498,
        -0.52286113, -0.0858261 ],
       ...,
       [-1.26942873,  0.06596834, -1.27693925, ..., -1.25033307,
        -0.6415088 , -0.40077455],
       [-1.25537501, -0.9337937 , -1.16263554, ...,  0.55721976,
         0.30089264,  2.17959258],
       [-0.6203227 , -1.10625265, -0.56264576, ..., -0.91575906,
        -0.34488964,  0.94742583]])

In [37]:
x4=lr.predict(X_test)
x5=dt.predict(X_test)
x6=bn.predict(X_test)

In [38]:
df5=pd.DataFrame(data=[x4,x5,x6])

In [39]:
df6=df5.T

In [40]:
df6

0  1  2
0   1  1  1
1   1  1  1
2   1  1  1
3   0  0  0
4   1  1  1
.. .. .. ..
89  1  1  1
90  1  1  1
91  1  1  1
92  1  0  0
93  1  1  1

[94 rows x 3 columns]

In [41]:
df6_X=df6.iloc[:,:]


In [42]:
final=lr2.predict(df6_X)

In [43]:
from sklearn.metrics import accuracy_score

In [44]:
accuracy_score(y_test, final)

0.9893617021276596

In [45]:
from sklearn.ensemble import StackingClassifier

In [46]:
df_X=df.iloc[:,:-1]
df_y=df.iloc[:,-1]

In [47]:
df_X=sc.fit_transform(df_X)

In [48]:
df_X.shape

(569, 30)

In [49]:
df_X_train, df_X_test, df_y_train, df_y_test = train_test_split(df_X, df_y, test_size=0.33)

In [50]:
estimators=[('lr',LogisticRegression()),('dt',DecisionTreeClassifier()),('bn',BernoulliNB())]

In [51]:
clf = StackingClassifier(estimators=estimators, final_estimator=LogisticRegression())

In [52]:
clf.fit(df_X_train,df_y_train)

StackingClassifier(estimators=[('lr', LogisticRegression()),
                               ('dt', DecisionTreeClassifier()),
                               ('bn', BernoulliNB())],
                   final_estimator=LogisticRegression())

In [53]:
final1=clf.predict(df_X_test)

In [54]:
accuracy_score(df_y_test, final1)

0.9680851063829787