In [3]:
import numpy as np
import io
import pandas as pd
import matplotlib.pyplot as plt

In [4]:
from google.colab import files
uploaded = files.upload()
data = pd.read_csv(io.BytesIO(uploaded['BuyComputer.csv']))
data.drop(columns=['User ID',],axis=1,inplace=True)
data.head()

Saving BuyComputer.csv to BuyComputer (1).csv


Age  EstimatedSalary  Purchased
0   19            19000          0
1   35            20000          0
2   26            43000          0
3   27            57000          0
4   19            76000          0

In [5]:
data

Age  EstimatedSalary  Purchased
0     19            19000          0
1     35            20000          0
2     26            43000          0
3     27            57000          0
4     19            76000          0
..   ...              ...        ...
395   46            41000          1
396   51            23000          1
397   50            20000          1
398   36            33000          0
399   49            36000          1

[400 rows x 3 columns]

# Declare label as last column in the source file

In [6]:
#Declaring X as all columns excluding last
X = data.iloc[:,:-1].values

#Declare label as last column in the source file
Y = data.iloc[:,-1].values


In [7]:
X

array([[    19,  19000],
       [    35,  20000],
       [    26,  43000],
       [    27,  57000],
       [    19,  76000],
       [    27,  58000],
       [    27,  84000],
       [    32, 150000],
       [    25,  33000],
       [    35,  65000],
       [    26,  80000],
       [    26,  52000],
       [    20,  86000],
       [    32,  18000],
       [    18,  82000],
       [    29,  80000],
       [    47,  25000],
       [    45,  26000],
       [    46,  28000],
       [    48,  29000],
       [    45,  22000],
       [    47,  49000],
       [    48,  41000],
       [    45,  22000],
       [    46,  23000],
       [    47,  20000],
       [    49,  28000],
       [    47,  30000],
       [    29,  43000],
       [    31,  18000],
       [    31,  74000],
       [    27, 137000],
       [    21,  16000],
       [    28,  44000],
       [    27,  90000],
       [    35,  27000],
       [    33,  28000],
       [    30,  49000],
       [    26,  72000],
       [    27,  31000],


In [28]:
# Splitting data
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test =  train_test_split(X,Y ,
                                   random_state=1, 
                                   test_size=0.25, 
                                   shuffle=True)

In [29]:
from os import XATTR_SIZE_MAX
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
X_train=sc.fit_transform(X_train)
X_test=sc.fit_transform(X_test)

In [30]:
X_train

array([[-1.68062015e+00, -5.92416706e-01],
       [ 8.69241193e-01,  5.63566526e-01],
       [-6.01832657e-01, -1.03702564e+00],
       [ 9.67312783e-01, -1.15558802e+00],
       [-2.09546297e-01, -5.62776110e-01],
       [ 1.82740063e-01,  8.00691292e-01],
       [-4.05689477e-01,  1.30458142e+00],
       [ 1.16345596e+00,  5.04285335e-01],
       [ 7.71169603e-01,  2.96801165e-01],
       [ 6.73098013e-01, -8.88822663e-01],
       [ 3.78883243e-01, -2.96010749e-01],
       [ 4.76954833e-01, -4.73854323e-01],
       [-2.09546297e-01,  1.18957591e-01],
       [ 3.78883243e-01,  8.93169951e-02],
       [-9.94119017e-01,  8.00691292e-01],
       [-6.99904247e-01,  1.39350321e+00],
       [ 3.78883243e-01, -5.03494919e-01],
       [ 3.78883243e-01, -5.03494919e-01],
       [-1.68062015e+00,  3.85722952e-01],
       [ 8.69241193e-01, -8.29541472e-01],
       [-9.94119017e-01, -1.12594743e+00],
       [-2.09546297e-01,  5.96763994e-02],
       [ 1.16345596e+00, -1.21486922e+00],
       [-2.

In [31]:
X_test

array([[-2.89053269e-01, -1.11810479e+00],
       [-1.89100270e-02, -3.15568669e-01],
       [-2.89053269e-01,  1.31816558e+00],
       [-1.89100270e-02,  1.43281360e+00],
       [-1.18953074e+00,  1.31816558e+00],
       [-1.08957774e-01, -2.00920651e-01],
       [-1.72981723e+00, -1.03211878e+00],
       [ 8.81567447e-01,  4.86967455e-01],
       [-7.39292006e-01, -1.54803486e+00],
       [ 7.91519700e-01,  1.97739168e+00],
       [-4.69148764e-01, -2.86620044e-04],
       [-1.89100270e-02,  2.83753844e-02],
       [-3.79101017e-01, -2.86620044e-04],
       [ 7.91519700e-01,  1.69077164e+00],
       [ 1.24175844e+00,  2.86333424e-01],
       [ 1.51190168e+00,  1.74809565e+00],
       [ 1.87209267e+00,  3.14995428e-01],
       [-1.09948300e+00, -4.01554682e-01],
       [-1.00943525e+00,  4.29643446e-01],
       [ 1.87209267e+00,  8.59573512e-01],
       [ 7.11377205e-02,  8.56993932e-02],
       [ 9.71615195e-01,  4.58305450e-01],
       [ 4.31328710e-01,  1.92006768e+00],
       [ 7.

In [32]:
#Variabes to calculate sigmoid function
y_pred = []
len_x = len(X_train[0])
w = []
b = 0.2
print(len_x)

2


In [33]:
entries = len(X_train[:,0])


In [34]:
entries

300

In [35]:
for weights in range(len_x):
  w.append(0)

In [36]:
w

[0, 0]

In [37]:
def sigmoid(z):
  return (1/(1+np.exp(-z)))


In [38]:
def predict(inputs):
  z=np.dot(inputs,w)+b
  h=sigmoid(z)
  for i in range((len(h))):
    if(h[i]>=0.5):
      h[i]=1
    else:
      h[i]=0
  return h
  


In [39]:
from scipy.optimize.minpack import shape
def loss_func(y,y1):
  total_loss=np.sum(-y*np.log(y1)-(1-y)*np.log(1-y1))
  m=y.shape[0]
  j=total_loss/m
  return j

In [40]:
dw = []
db = 0
J = 0
alpha = 0.1
for x in range(len_x):
  dw.append(0)

In [41]:
for i in range(3000):
    z = np.dot(X_train, w) + b
    y_pred = sigmoid(z)
    l = loss_func(y_train, y_pred)
    dw = np.dot((y_pred-y_train).T, X_train)/X_train.shape[0]
    db = np.mean(y_pred-y_train)
    w = w - alpha * dw
    b = b - alpha* db
    print("Round:",i,"Weight:",w,"Bias:",b,"loss:",l)

Round: 0 Weight: [0.02798952 0.01948718] Bias: 0.1786832669354189 loss: 0.7308055360482587
Round: 1 Weight: [0.05520582 0.03837745] Bias: 0.1578962144778177 loss: 0.7148525737192114
Round: 2 Weight: [0.08166961 0.05668866] Bias: 0.13762899877724738 loss: 0.6997669509965344
Round: 3 Weight: [0.10740265 0.07443931] Bias: 0.11787086089217322 loss: 0.6855026535175537
Round: 4 Weight: [0.13242744 0.09164833] Bias: 0.09861029481199307 loss: 0.6720144996585421
Round: 5 Weight: [0.15676693 0.1083349 ] Bias: 0.07983520695336749 loss: 0.6592584819586713
Round: 6 Weight: [0.18044433 0.12451825] Bias: 0.06153306430931978 loss: 0.6471920377296279
Round: 7 Weight: [0.20348285 0.1402175 ] Bias: 0.04369102939349751 loss: 0.6357742539644363
Round: 8 Weight: [0.22590558 0.15545155] Bias: 0.026296080965820038 loss: 0.6249660131448623
Round: 9 Weight: [0.24773532 0.17023894] Bias: 0.009335120225391527 loss: 0.6147300873435252
Round: 10 Weight: [0.26899444 0.18459779] Bias: -0.007204937294006394 loss: 0.60

In [42]:
X_train


array([[-1.68062015e+00, -5.92416706e-01],
       [ 8.69241193e-01,  5.63566526e-01],
       [-6.01832657e-01, -1.03702564e+00],
       [ 9.67312783e-01, -1.15558802e+00],
       [-2.09546297e-01, -5.62776110e-01],
       [ 1.82740063e-01,  8.00691292e-01],
       [-4.05689477e-01,  1.30458142e+00],
       [ 1.16345596e+00,  5.04285335e-01],
       [ 7.71169603e-01,  2.96801165e-01],
       [ 6.73098013e-01, -8.88822663e-01],
       [ 3.78883243e-01, -2.96010749e-01],
       [ 4.76954833e-01, -4.73854323e-01],
       [-2.09546297e-01,  1.18957591e-01],
       [ 3.78883243e-01,  8.93169951e-02],
       [-9.94119017e-01,  8.00691292e-01],
       [-6.99904247e-01,  1.39350321e+00],
       [ 3.78883243e-01, -5.03494919e-01],
       [ 3.78883243e-01, -5.03494919e-01],
       [-1.68062015e+00,  3.85722952e-01],
       [ 8.69241193e-01, -8.29541472e-01],
       [-9.94119017e-01, -1.12594743e+00],
       [-2.09546297e-01,  5.96763994e-02],
       [ 1.16345596e+00, -1.21486922e+00],
       [-2.

In [43]:
y_pred=predict(X_test)

In [44]:
y_pred

array([0., 0., 0., 1., 0., 0., 0., 1., 0., 1., 0., 0., 0., 1., 1., 1., 1.,
       0., 0., 1., 0., 1., 1., 0., 0., 0., 1., 1., 1., 1., 0., 0., 0., 1.,
       0., 0., 0., 0., 0., 0., 1., 1., 0., 0., 1., 0., 0., 1., 0., 1., 0.,
       0., 0., 0., 0., 0., 1., 0., 1., 1., 0., 0., 1., 0., 0., 1., 0., 0.,
       1., 0., 1., 0., 1., 0., 0., 1., 0., 0., 0., 0., 0., 0., 1., 0., 0.,
       0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 1., 1., 0., 0., 0.])

In [45]:
#print actual and predicted values in a table
print("actual Value\tpredicted values")
for i in range(len(y_test)):
    print(y_test[i],"\t\t",int(y_pred[i]))

actual Value	predicted values
0 		 0
0 		 0
1 		 0
1 		 1
0 		 0
0 		 0
0 		 0
1 		 1
0 		 0
0 		 1
0 		 0
0 		 0
0 		 0
1 		 1
1 		 1
1 		 1
1 		 1
0 		 0
0 		 0
1 		 1
0 		 0
1 		 1
1 		 1
0 		 0
1 		 0
0 		 0
1 		 1
0 		 1
1 		 1
0 		 1
0 		 0
0 		 0
0 		 0
1 		 1
0 		 0
0 		 0
0 		 0
0 		 0
1 		 0
0 		 0
1 		 1
1 		 1
0 		 0
0 		 0
1 		 1
1 		 0
1 		 0
1 		 1
0 		 0
1 		 1
0 		 0
0 		 0
1 		 0
1 		 0
1 		 0
0 		 0
1 		 1
0 		 0
1 		 1
1 		 1
0 		 0
0 		 0
0 		 1
0 		 0
1 		 0
1 		 1
0 		 0
0 		 0
0 		 1
0 		 0
0 		 1
0 		 0
1 		 1
0 		 0
0 		 0
1 		 1
0 		 0
0 		 0
0 		 0
0 		 0
0 		 0
1 		 0
1 		 1
0 		 0
0 		 0
0 		 0
1 		 0
0 		 0
1 		 0
0 		 0
1 		 0
1 		 1
1 		 0
0 		 0
0 		 0
1 		 1
1 		 1
1 		 0
0 		 0
0 		 0


In [46]:
x=0
for i in range(len(y_test)):
  if(y_test[i]==y_pred[i]):
    x+=1
print((x/len(y_test))*100)


79.0


In [47]:
from sklearn.linear_model import LogisticRegression
LR = LogisticRegression()
from sklearn.metrics import  accuracy_score
#Fit
LR.fit(X_train,y_train)

#predicting the test label with LR. Predict always takes X as input
y_test_pred = LR.predict(X_test)
accuracy = accuracy_score(y_test, y_test_pred)*100
print("Accuracy: ", accuracy,"%")

Accuracy:  78.0 %


In [48]:
y_pred1=predict(X)

In [50]:
print("actual Value\tpredicted values")
for i in range(len(Y)):
    print(Y[i],"\t\t",int(y_pred1[i]))

actual Value	predicted values
0 		 1
0 		 1
0 		 1
0 		 1
0 		 1
0 		 1
0 		 1
1 		 1
0 		 1
0 		 1
0 		 1
0 		 1
0 		 1
0 		 1
0 		 1
0 		 1
1 		 1
1 		 1
1 		 1
1 		 1
1 		 1
1 		 1
1 		 1
1 		 1
1 		 1
1 		 1
1 		 1
1 		 1
0 		 1
0 		 1
0 		 1
1 		 1
0 		 1
0 		 1
0 		 1
0 		 1
0 		 1
0 		 1
0 		 1
0 		 1
0 		 1
0 		 1
0 		 1
0 		 1
0 		 1
0 		 1
0 		 1
0 		 1
1 		 1
0 		 1
0 		 1
0 		 1
0 		 1
0 		 1
0 		 1
0 		 1
0 		 1
0 		 1
0 		 1
0 		 1
0 		 1
0 		 1
0 		 1
1 		 1
0 		 1
0 		 1
0 		 1
0 		 1
0 		 1
0 		 1
0 		 1
0 		 1
0 		 1
0 		 1
0 		 1
1 		 1
0 		 1
0 		 1
0 		 1
0 		 1
0 		 1
0 		 1
0 		 1
0 		 1
0 		 1
1 		 1
0 		 1
0 		 1
0 		 1
0 		 1
0 		 1
0 		 1
0 		 1
0 		 1
0 		 1
0 		 1
0 		 1
1 		 1
0 		 1
0 		 1
0 		 1
0 		 1
0 		 1
1 		 1
0 		 1
0 		 1
0 		 1
0 		 1
0 		 1
0 		 1
0 		 1
0 		 1
0 		 1
0 		 1
0 		 1
0 		 1
0 		 1
0 		 1
0 		 1
0 		 1
0 		 1
0 		 1
0 		 1
0 		 1
0 		 1
0 		 1
0 		 1
0 		 1
0 		 1
0 		 1
0 		 1
0 		 1
0 		 1
0 		 1
0 		 1
0 		 1
0 		 1
1 		 1
0 		